version: '3.8'

services:
  postgres-rochela:
    image: postgres:15-alpine
    container_name: postgres_rochela_container
    environment:
      POSTGRES_DB: rochela_db
      POSTGRES_USER: rochela_user
      POSTGRES_PASSWORD: rochela_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_rochela_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_rochela_data: