spring:
  application:
    name: rochelasystem
  datasource:
    url: jdbc:postgresql://localhost:5432/rochela_db
    driver-class-name: org.postgresql.Driver
    username: rochela_user
    password: rochela_password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

exportacion:
  recepcion:
    pendiente:
      enabled: false
  google:
    spreadsheet-id: 1SzgPLmy6m59KiH7tVGuU9lZkgZGVYSPs3U41xMUjHzM
    credentials-path: var/secrets/google-credentials.json
    sheets:
      rendimiento: "Materia Prima y rendimiento"
      recepciones: "Recepciones y proveedores"
      etapas: "Etapas lote"
